### PR TITLE
Make db config more human readable.

### PR DESCRIPTION
**Pull request by Faryshta**
Simple change reducing the code a little and making it more easy to read to humans.

PHP5.3 compatible, in a future it might be cool to use [ ] instead of array( )

### CODE REVIEW

**Comment by onkelzfreak1988** [comment]
maybe you forgot to defined the DB_PREFIX ???

**Comment by onkelzfreak1988** [comment]
sry i see it now

**Comment by Faryshta** [comment]
:D

2012/9/24 Oliver notifications@github.com

**Comment by Faryshta** [comment]
BTW. What do you think about turning the $loader variable into a global?

Its the most used bar, I think it can be a good idea.

**Comment by feulf** [comment]
Hey Faryshta,
I've cherry-picked the changes to .gitignore, and the indentation, about:
- cleaning the bootstrap.php... I'll think about this change
- swp file ignored, there are too many files OS related and Editor related that should be ignored, so this should be just a local change, and same for deleted files.

Thanks for your contribution, very appreciated!

**Comment by Faryshta** [comment]
Awesome, thanks.

I was thinking on put all the configurations initializers on the bootstraps and the rest on index.php since I am thinking on the possibility  to have more than one page at the same server.

**Comment by feulf** [comment]
About $loader global is a no-no, starting from PHP 5.4 global is not supported. 

About the organization of bootstrap and index, they are separated to keep the code DRY, if you want to create multiple apps that use the same codebase of the framework, all you've to do is to change the configuration in config file.

**Comment by Faryshta** [comment]
Some configuration must work for all the pages on the same server, like the
database that is what I am trying to do.

I didn't knew that global was deprecated. Thanks for the info.

2012/9/25 Federico Ulfo notifications@github.com

**Comment by Faryshta** [comment]
Globals do still work on php 5.4, what doesn't work is register_globals
which is a configuration option.}

http://php.net/releases/5_4_0.php

http://mx.php.net/manual/en/security.globals.php

http://php.net/manual/en/ini.core.php#ini.register-globals

Register globals takes the variables from $_GET, $_POST, $_COOKIE and
$_SESSION and make them globally available making $something an alias of
$_GET['something'].

It has been by default since php4.2 so its not even used anymore.

Global variables on the other hand got no changes from the php5.4 update
http://php.net/manual/en/reserved.variables.globals.php

2012/9/25 Faryshta angeldelcaos@gmail.com

**Comment by Faryshta** [comment]
Correction: It has been OFF by default since php4.2 so its not used anymore.

2012/9/25 Faryshta angeldelcaos@gmail.com

**Comment by feulf** [comment]
Well, using global is considered bad practice, so I could avoid it anyway, let's use dependency injection instead.

**Comment by Faryshta** [comment]
I have never heard that its a bad practice.

Ok I will try it on a new branch when I have more time so we can try it
there. Do you agree?

2012/9/25 Federico Ulfo notifications@github.com

**Pull request closed without merging**
